# Generated by Django 4.2.1 on 2023-05-17 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('code_filter', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_value_parsing', models.IntegerField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(to='admin_parser.category')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Procesing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complate', models.BooleanField(default=False)),
                ('count_nice_parse', models.IntegerField()),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_finish', models.DateTimeField()),
                ('id_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_parser.filter')),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16)),
                ('have_telegram', models.BooleanField(default=False)),
                ('have_viber', models.BooleanField(default=False)),
                ('have_whatsApp', models.BooleanField(default=False)),
                ('interested', models.BooleanField(default=False)),
                ('massage_interested', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('nice_client', models.BooleanField(default=False)),
                ('complate', models.BooleanField(default=False)),
                ('filter_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_parser.filter')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_parser.manager')),
            ],
        ),
    ]
